In [ ]:
# !pip install tensorflow_text
!pip install transformers
# !pip install simpletransformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 59.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 60.5 MB/s eta 0:00:00


In [ ]:
import pandas as pd

In [ ]:
df_ekonomi = pd.read_csv('ekonomi.csv')
df_gayaHidup = pd.read_csv('gayaHidup.csv')
df_hiburan = pd.read_csv('hiburan.csv')
df_hukumKriminal = pd.read_csv('hukumKriminal.csv')
df_internasional = pd.read_csv('internasional.csv')
df_keamanan = pd.read_csv('keamanan.csv')
df_olahraga = pd.read_csv('olahraga.csv')
df_ototmotif = pd.read_csv('otomtif.csv')
df_politik = pd.read_csv('politik.csv')
df_teknologi = pd.read_csv('teknolog.csv')

df_ekonomi['label'] = 'Ekonomi'
df_gayaHidup['label'] = 'GayaHidup'
df_hiburan['label'] = 'Hiburan'
df_hukumKriminal['label'] = 'HukumKrimnial'
df_internasional['label'] = 'Internasional'
df_keamanan['label'] = 'Keamanan'
df_olahraga['label'] = 'Olahraga'
df_ototmotif['label'] = 'Otomotif'
df_politik['label'] = 'Politik'
df_teknologi['label'] = 'Teknologi'
print("ekonomi",df_ekonomi.shape)
print("gaya Hidup",df_gayaHidup.shape)
print("hiburan",df_hiburan.shape)
print("hukum Kriminal",df_hukumKriminal.shape)
print("internasional",df_internasional.shape)
print("keamanan",df_keamanan.shape)
print("olahraga",df_olahraga.shape)
print("otomotif",df_ototmotif.shape)
print("politik",df_politik.shape)
print("teknologi",df_teknologi.shape)
df_ekonomi, df_Test_ekonomi = df_ekonomi.iloc[:400, :], df_ekonomi.iloc[400:, :]
df_gayaHidup, df_Test_gayaHidup = df_gayaHidup.iloc[:400, :], df_gayaHidup.iloc[400:, :]
df_hiburan, df_Test_hiburan = df_hiburan.iloc[:400, :], df_hiburan.iloc[400:, :]
df_hukumKriminal, df_Test_hukumKriminal = df_hukumKriminal.iloc[:400, :], df_hukumKriminal.iloc[400:, :]
df_internasional, df_Test_internasional = df_internasional.iloc[:400, :], df_internasional.iloc[400:, :]
df_keamanan, df_Test_keamanan = df_keamanan.iloc[:400, :], df_keamanan.iloc[400:, :]
df_olahraga, df_Test_olahraga = df_olahraga.iloc[:400, :], df_olahraga.iloc[400:, :]
df_ototmotif, df_Test_ototmotif = df_ototmotif.iloc[:400, :], df_ototmotif.iloc[400:, :]
df_politik, df_Test_politik = df_politik.iloc[:400, :], df_politik.iloc[400:, :]
df_teknologi, df_Test_teknologi = df_teknologi.iloc[:400, :], df_teknologi.iloc[400:, :]
print("train ekonomi",df_ekonomi.shape)
print("train gaya Hidup",df_gayaHidup.shape)
print("train hiburan",df_hiburan.shape)
print("train hukum Kriminal",df_hukumKriminal.shape)
print("train internasional",df_internasional.shape)
print("train keamanan",df_keamanan.shape)
print("train olahraga",df_olahraga.shape)
print("train otomotif",df_ototmotif.shape)
print("train politik",df_politik.shape)
print("train teknologi",df_teknologi.shape)
df_train  = pd.concat([df_ekonomi,df_gayaHidup,df_hiburan,df_hukumKriminal,df_internasional,df_keamanan,df_olahraga,df_ototmotif,df_politik,df_teknologi])
df_test = pd.concat([df_Test_ekonomi,df_Test_gayaHidup,df_Test_hiburan,df_Test_hukumKriminal,df_Test_internasional,df_Test_keamanan,df_Test_olahraga,df_Test_ototmotif,df_Test_politik,df_Test_teknologi])
df_train = df_train.sample(frac =1).reset_index(drop = True)
df_test = df_test.sample(frac = 1).reset_index(drop = True)
df_train.drop(columns = ["Unnamed: 0"], inplace = True)
df_test.drop(columns = "Unnamed: 0", inplace = True)

ekonomi (490, 3)
gaya Hidup (490, 3)
hiburan (490, 3)
hukum Kriminal (490, 3)
internasional (490, 3)
keamanan (643, 3)
olahraga (490, 3)
otomotif (490, 3)
politik (490, 3)
teknologi (490, 3)
train ekonomi (400, 3)
train gaya Hidup (400, 3)
train hiburan (400, 3)
train hukum Kriminal (400, 3)
train internasional (400, 3)
train keamanan (400, 3)
train olahraga (400, 3)
train otomotif (400, 3)
train politik (400, 3)
train teknologi (400, 3)


In [ ]:
X_train = df_train.iloc[:, -2].values
y_train = df_train.iloc[:, -1].values

X_test = df_test.iloc[:, -2].values
y_test = df_test.iloc[:, -1].values

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from keras.datasets import fashion_mnist
from keras.models import Sequential, Model
from keras.layers import Dense, Input

In [ ]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

In [ ]:
encoder.fit(y_train)

LabelEncoder()

In [ ]:
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
num_labels = len(np.unique(y_test))

In [ ]:
num_labels

10

In [ ]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
label = encoder.inverse_transform(np.unique(y_train))

In [ ]:
id2label = {int(i): j for i, j in zip(np.unique(y_train), label)}

In [ ]:
label2id = {i: int(j) for i, j in zip(label, np.unique(y_train))}

In [ ]:
label2id

{'Ekonomi': 0,
 'GayaHidup': 1,
 'Hiburan': 2,
 'HukumKrimnial': 3,
 'Internasional': 4,
 'Keamanan': 5,
 'Olahraga': 6,
 'Otomotif': 7,
 'Politik': 8,
 'Teknologi': 9}

In [ ]:
df_train.rename(columns= {'0': 'text'}, inplace = True)

In [ ]:
df_train['label'] = df_train['label'].replace(label2id)

In [ ]:
df_train

text  label
0     Daftar Kasus Besar yang Ditangani Dirdik KPK B...      3
1     Eks Kapolri Da'i Bachtiar dan Purnawirawan TNI...      8
2     Indonesia Galang Komitmen Bersama Percepat Tra...      2
3     Hasil Soccer Champions Tour: Bellingham Cetak ...      6
4     ESDM Kejar Bengkel Konversi Motor Listrik Tamb...      0
...                                                 ...    ...
3995  Babak 1: Arief Catur Kartu Merah, Persija Ungg...      6
3996  Indonesia Rugi Rp551 T Imbas Makanan Terbuang ...      0
3997  Tiko Masih Tidur di Pos Keamanan meski Rumah B...      5
3998  Puan Maharani Temui Cak Imin Siang Ini Bahas K...      8
3999  Ahli Sindir KPK Minta Maaf: Kesalahan Tak Bisa...      3

[4000 rows x 2 columns]

In [ ]:
from transformers import BertTokenizer, TFBertModel, Trainer, TrainingArguments,BertForSequenceClassification

model_name='cahya/bert-base-indonesian-522M'
tokenizer = BertTokenizer.from_pretrained(model_name)
# model = TFBertModel.from_pretrained(model_name, num_labels=num_labels)


In [ ]:
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=num_labels, id2label = id2label, label2id = label2id)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cahya/bert-base-indonesian-522M and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
encoded_texts = tokenizer(X_train.tolist(), padding=True, return_tensors="pt")

In [ ]:
df_train['text'][:1].values.tolist()

['Daftar Kasus Besar yang Ditangani Dirdik KPK Brigjen Asep Guntur']

In [ ]:
tokenizer(df_train['text'][:1].values.tolist())

{'input_ids': [[3, 3217, 3711, 1795, 1510, 12372, 1847, 9597, 15233, 20719, 20964, 20293, 1]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
df_train_list = df_train['text'].values.tolist()

In [ ]:
df_train_list

In [ ]:
len(df_train_list)

4000

In [ ]:
X_train_token = []
for i in df_train_list:
  X_train_token.append(tokenizer(i, truncation = True, max_length= 512))

In [ ]:
X_train_token

In [ ]:
# Buat data loader untuk data pelatihan
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
import torch

In [ ]:
encoded_texts.input_ids

tensor([[    3,  3217,  3711,  ...,     2,     2,     2],
        [    3,  2163, 23125,  ...,     2,     2,     2],
        [    3,  1766, 20562,  ...,     2,     2,     2],
        ...,
        [    3,  5146,  1016,  ...,     2,     2,     2],
        [    3,  3884,  1487,  ...,     2,     2,     2],
        [    3,  3677,  6695,  ...,     2,     2,     2]])

In [ ]:
len(X_train.tolist())

4000

In [ ]:
encoded_texts.attention_mask

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [ ]:
train_dataset = TensorDataset(encoded_texts.input_ids, encoded_texts.attention_mask, torch.tensor(y_train.tolist()))


In [ ]:
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

In [ ]:
!mkdir /results

In [ ]:
next(iter(train_loader))

In [ ]:
!pip install transformers[torch]
!pip install accelerate -U

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 6.2 MB/s eta 0:00:00


In [ ]:
training_args = TrainingArguments(
    output_dir="/results",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    logging_steps=50,
    save_steps=100,
    evaluation_strategy="epoch",
)



In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=X_train_token,
)

# Mulai pelatihan
trainer.train()


/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


ValueError: ignored