In [ ]:
!pip install transformers
!pip install Sastrawi

In [ ]:
import torch
from tqdm.notebook import tqdm

from transformers import BertTokenizer
from torch.utils.data import TensorDataset

from transformers import BertForSequenceClassification

In [ ]:
import pandas as pd

In [ ]:
df_ekonomi = pd.read_csv('ekonomi.csv')
df_gayaHidup = pd.read_csv('gayaHidup.csv')
df_hiburan = pd.read_csv('hiburan.csv')
df_hukumKriminal = pd.read_csv('hukumKriminal.csv')
df_internasional = pd.read_csv('internasional.csv')
df_keamanan = pd.read_csv('keamanan.csv')
df_olahraga = pd.read_csv('olahraga.csv')
df_ototmotif = pd.read_csv('otomtif.csv')
df_politik = pd.read_csv('politik.csv')
df_teknologi = pd.read_csv('teknolog.csv')

df_ekonomi['label'] = 'Ekonomi'
df_gayaHidup['label'] = 'GayaHidup'
df_hiburan['label'] = 'Hiburan'
df_hukumKriminal['label'] = 'HukumKrimnial'
df_internasional['label'] = 'Internasional'
df_keamanan['label'] = 'Keamanan'
df_olahraga['label'] = 'Olahraga'
df_ototmotif['label'] = 'Otomotif'
df_politik['label'] = 'Politik'
df_teknologi['label'] = 'Teknologi'
print("ekonomi",df_ekonomi.shape)
print("gaya Hidup",df_gayaHidup.shape)
print("hiburan",df_hiburan.shape)
print("hukum Kriminal",df_hukumKriminal.shape)
print("internasional",df_internasional.shape)
print("keamanan",df_keamanan.shape)
print("olahraga",df_olahraga.shape)
print("otomotif",df_ototmotif.shape)
print("politik",df_politik.shape)
print("teknologi",df_teknologi.shape)
df_ekonomi, df_Test_ekonomi = df_ekonomi.iloc[:100, :], df_ekonomi.iloc[100:150, :]
df_gayaHidup, df_Test_gayaHidup = df_gayaHidup.iloc[:100, :], df_gayaHidup.iloc[100:150, :]
df_hiburan, df_Test_hiburan = df_hiburan.iloc[:100, :], df_hiburan.iloc[100:150, :]
df_hukumKriminal, df_Test_hukumKriminal = df_hukumKriminal.iloc[:100, :], df_hukumKriminal.iloc[100:150, :]
df_internasional, df_Test_internasional = df_internasional.iloc[:100, :], df_internasional.iloc[100:150, :]
df_keamanan, df_Test_keamanan = df_keamanan.iloc[:100, :], df_keamanan.iloc[100:150, :]
df_olahraga, df_Test_olahraga = df_olahraga.iloc[:100, :], df_olahraga.iloc[100:150, :]
df_ototmotif, df_Test_ototmotif = df_ototmotif.iloc[:100, :], df_ototmotif.iloc[100:150, :]
df_politik, df_Test_politik = df_politik.iloc[:100, :], df_politik.iloc[100:150, :]
df_teknologi, df_Test_teknologi = df_teknologi.iloc[:100, :], df_teknologi.iloc[100:150, :]
print("train ekonomi",df_ekonomi.shape)
print("train gaya Hidup",df_gayaHidup.shape)
print("train hiburan",df_hiburan.shape)
print("train hukum Kriminal",df_hukumKriminal.shape)
print("train internasional",df_internasional.shape)
print("train keamanan",df_keamanan.shape)
print("train olahraga",df_olahraga.shape)
print("train otomotif",df_ototmotif.shape)
print("train politik",df_politik.shape)
print("train teknologi",df_teknologi.shape)
df_train  = pd.concat([df_ekonomi,df_gayaHidup,df_hiburan,df_hukumKriminal,df_internasional,df_keamanan,df_olahraga,df_ototmotif,df_politik,df_teknologi])
df_test = pd.concat([df_Test_ekonomi,df_Test_gayaHidup,df_Test_hiburan,df_Test_hukumKriminal,df_Test_internasional,df_Test_keamanan,df_Test_olahraga,df_Test_ototmotif,df_Test_politik,df_Test_teknologi])
df_train = df_train.sample(frac =1).reset_index(drop = True)
df_test = df_test.sample(frac = 1).reset_index(drop = True)
df_train.drop(columns = ["Unnamed: 0"], inplace = True)
df_test.drop(columns = "Unnamed: 0", inplace = True)

In [ ]:
import numpy as np
import nltk
nltk.download('stopwords')
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
X_train = df_train.iloc[:, -2].values
y_train = df_train.iloc[:, -1].values

X_test = df_test.iloc[:, -2].values
y_test = df_test.iloc[:, -1].values

In [ ]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

In [ ]:
encoder.fit(y_train)

LabelEncoder()

In [ ]:
y_train = encoder.transform(y_train)

In [ ]:
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([7, 4, 9, 2, 8, 0, 8, 0, 9, 0, 7, 3, 6, 9, 8, 1, 2, 4, 5, 4, 6, 6,
       5, 7, 9, 4, 4, 1, 2, 3, 7, 5, 5, 6, 7, 1, 1, 3, 8, 2, 3, 1, 5, 6,
       5, 4, 8, 7, 6, 9, 4, 8, 0, 3, 8, 7, 1, 1, 9, 6, 2, 1, 8, 7, 0, 1,
       1, 3, 4, 0, 1, 8, 9, 3, 4, 1, 5, 9, 6, 0, 4, 0, 3, 0, 4, 8, 3, 7,
       8, 6, 8, 5, 3, 2, 8, 8, 1, 5, 3, 3, 2, 6, 5, 7, 3, 7, 0, 5, 1, 9,
       8, 8, 9, 7, 4, 9, 7, 7, 2, 5, 4, 6, 4, 6, 8, 4, 4, 7, 6, 6, 2, 9,
       7, 8, 2, 2, 7, 6, 9, 7, 4, 2, 0, 9, 7, 4, 4, 4, 1, 8, 3, 7, 5, 8,
       2, 6, 4, 9, 0, 6, 8, 5, 9, 1, 8, 0, 1, 9, 1, 5, 5, 4, 4, 6, 6, 6,
       3, 1, 2, 7, 8, 8, 4, 8, 5, 3, 6, 0, 1, 7, 7, 7, 4, 4, 4, 9, 9, 5,
       1, 7, 4, 1, 6, 7, 3, 6, 5, 9, 8, 5, 7, 8, 5, 9, 1, 0, 3, 3, 1, 4,
       3, 2, 0, 5, 5, 8, 3, 8, 1, 5, 6, 0, 0, 8, 5, 5, 3, 6, 6, 2, 3, 9,
       7, 5, 6, 6, 6, 2, 9, 6, 2, 7, 1, 4, 2, 8, 1, 8, 2, 7, 8, 5, 0, 7,
       2, 7, 8, 9, 1, 5, 8, 3, 7, 8, 1, 5, 9, 5, 0, 1, 2, 9, 1, 5, 2, 9,
       6, 3, 4, 4, 2, 5, 3, 6, 0, 6, 5, 9, 4, 2, 6,

In [ ]:
y_test

array([1, 3, 5, 6, 6, 6, 6, 2, 2, 1, 6, 2, 9, 8, 4, 2, 6, 4, 7, 4, 3, 5,
       3, 9, 0, 3, 0, 6, 2, 2, 0, 8, 2, 4, 8, 1, 3, 1, 9, 3, 8, 4, 0, 4,
       5, 4, 7, 8, 7, 2, 0, 5, 1, 0, 8, 8, 0, 3, 8, 4, 3, 1, 2, 8, 2, 5,
       9, 8, 5, 9, 7, 1, 7, 7, 6, 1, 3, 1, 9, 7, 6, 6, 2, 3, 1, 2, 2, 4,
       9, 9, 8, 3, 1, 8, 1, 1, 5, 5, 7, 4, 7, 7, 1, 3, 5, 7, 9, 5, 0, 5,
       1, 1, 0, 0, 3, 0, 0, 0, 1, 2, 1, 9, 1, 5, 2, 0, 3, 0, 3, 7, 4, 6,
       5, 3, 3, 5, 3, 7, 9, 2, 4, 6, 4, 9, 7, 9, 0, 6, 5, 6, 5, 2, 4, 4,
       6, 1, 9, 1, 8, 4, 5, 9, 8, 4, 7, 7, 9, 5, 0, 0, 5, 5, 9, 9, 4, 8,
       0, 4, 5, 1, 6, 5, 5, 9, 8, 2, 2, 5, 3, 7, 7, 0, 2, 7, 0, 6, 3, 8,
       8, 9, 6, 8, 8, 2, 0, 8, 1, 8, 2, 7, 3, 9, 2, 1, 6, 2, 4, 1, 4, 3,
       4, 8, 7, 4, 0, 7, 8, 1, 3, 4, 0, 0, 3, 8, 3, 1, 6, 7, 1, 2, 5, 8,
       3, 5, 0, 0, 0, 5, 0, 9, 3, 5, 9, 1, 4, 7, 7, 2, 2, 6, 5, 9, 6, 2,
       5, 0, 0, 6, 6, 4, 3, 3, 8, 6, 6, 0, 1, 3, 7, 0, 0, 7, 2, 2, 1, 3,
       3, 2, 4, 4, 4, 8, 6, 1, 1, 2, 9, 3, 3, 6, 0,

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased',
                                          do_lower_case=True)

In [ ]:
encoded_data_train = tokenizer.batch_encode_plus(
    X_train,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

encoded_data_test = tokenizer.batch_encode_plus(
    X_test,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2393: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [ ]:
encoded_data_train

{'input_ids': tensor([[  101, 23769,  2319,  ...,     0,     0,     0],
        [  101,  2038,  4014,  ...,     0,     0,     0],
        [  101,  8292, 17728,  ...,     0,     0,     0],
        ...,
        [  101,  2079,  2050,  ...,     0,     0,     0],
        [  101,  1021, 12849,  ...,     0,     0,     0],
        [  101,  1017, 26473,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [ ]:
input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(y_train)

input_ids_test = encoded_data_test['input_ids']
attention_masks_test = encoded_data_test['attention_mask']
labels_test = torch.tensor(y_test)



In [ ]:
labels_train

tensor([7, 4, 9, 2, 8, 0, 8, 0, 9, 0, 7, 3, 6, 9, 8, 1, 2, 4, 5, 4, 6, 6, 5, 7,
        9, 4, 4, 1, 2, 3, 7, 5, 5, 6, 7, 1, 1, 3, 8, 2, 3, 1, 5, 6, 5, 4, 8, 7,
        6, 9, 4, 8, 0, 3, 8, 7, 1, 1, 9, 6, 2, 1, 8, 7, 0, 1, 1, 3, 4, 0, 1, 8,
        9, 3, 4, 1, 5, 9, 6, 0, 4, 0, 3, 0, 4, 8, 3, 7, 8, 6, 8, 5, 3, 2, 8, 8,
        1, 5, 3, 3, 2, 6, 5, 7, 3, 7, 0, 5, 1, 9, 8, 8, 9, 7, 4, 9, 7, 7, 2, 5,
        4, 6, 4, 6, 8, 4, 4, 7, 6, 6, 2, 9, 7, 8, 2, 2, 7, 6, 9, 7, 4, 2, 0, 9,
        7, 4, 4, 4, 1, 8, 3, 7, 5, 8, 2, 6, 4, 9, 0, 6, 8, 5, 9, 1, 8, 0, 1, 9,
        1, 5, 5, 4, 4, 6, 6, 6, 3, 1, 2, 7, 8, 8, 4, 8, 5, 3, 6, 0, 1, 7, 7, 7,
        4, 4, 4, 9, 9, 5, 1, 7, 4, 1, 6, 7, 3, 6, 5, 9, 8, 5, 7, 8, 5, 9, 1, 0,
        3, 3, 1, 4, 3, 2, 0, 5, 5, 8, 3, 8, 1, 5, 6, 0, 0, 8, 5, 5, 3, 6, 6, 2,
        3, 9, 7, 5, 6, 6, 6, 2, 9, 6, 2, 7, 1, 4, 2, 8, 1, 8, 2, 7, 8, 5, 0, 7,
        2, 7, 8, 9, 1, 5, 8, 3, 7, 8, 1, 5, 9, 5, 0, 1, 2, 9, 1, 5, 2, 9, 6, 3,
        4, 4, 2, 5, 3, 6, 0, 6, 5, 9, 4,

In [ ]:
labels_test

tensor([1, 3, 5, 6, 6, 6, 6, 2, 2, 1, 6, 2, 9, 8, 4, 2, 6, 4, 7, 4, 3, 5, 3, 9,
        0, 3, 0, 6, 2, 2, 0, 8, 2, 4, 8, 1, 3, 1, 9, 3, 8, 4, 0, 4, 5, 4, 7, 8,
        7, 2, 0, 5, 1, 0, 8, 8, 0, 3, 8, 4, 3, 1, 2, 8, 2, 5, 9, 8, 5, 9, 7, 1,
        7, 7, 6, 1, 3, 1, 9, 7, 6, 6, 2, 3, 1, 2, 2, 4, 9, 9, 8, 3, 1, 8, 1, 1,
        5, 5, 7, 4, 7, 7, 1, 3, 5, 7, 9, 5, 0, 5, 1, 1, 0, 0, 3, 0, 0, 0, 1, 2,
        1, 9, 1, 5, 2, 0, 3, 0, 3, 7, 4, 6, 5, 3, 3, 5, 3, 7, 9, 2, 4, 6, 4, 9,
        7, 9, 0, 6, 5, 6, 5, 2, 4, 4, 6, 1, 9, 1, 8, 4, 5, 9, 8, 4, 7, 7, 9, 5,
        0, 0, 5, 5, 9, 9, 4, 8, 0, 4, 5, 1, 6, 5, 5, 9, 8, 2, 2, 5, 3, 7, 7, 0,
        2, 7, 0, 6, 3, 8, 8, 9, 6, 8, 8, 2, 0, 8, 1, 8, 2, 7, 3, 9, 2, 1, 6, 2,
        4, 1, 4, 3, 4, 8, 7, 4, 0, 7, 8, 1, 3, 4, 0, 0, 3, 8, 3, 1, 6, 7, 1, 2,
        5, 8, 3, 5, 0, 0, 0, 5, 0, 9, 3, 5, 9, 1, 4, 7, 7, 2, 2, 6, 5, 9, 6, 2,
        5, 0, 0, 6, 6, 4, 3, 3, 8, 6, 6, 0, 1, 3, 7, 0, 0, 7, 2, 2, 1, 3, 3, 2,
        4, 4, 4, 8, 6, 1, 1, 2, 9, 3, 3,

In [ ]:
dataset_train = TensorDataset(input_ids_train, attention_masks_train, labels_train)
dataset_test = TensorDataset(input_ids_test, attention_masks_test, labels_test)

In [ ]:
dataset_train

In [ ]:
len(np.unique(y_train))


10

In [ ]:
model = BertForSequenceClassification.from_pretrained("bert-base-uncased",
                                                      num_labels= len(np.unique(y_train)),
                                                      output_attentions=False,
                                                      output_hidden_states=False)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

batch_size = 3

dataloader_train = DataLoader(dataset_train,
                              sampler=RandomSampler(dataset_train),
                              batch_size=batch_size)

dataloader_validation = DataLoader(dataset_test,
                                   sampler=SequentialSampler(dataset_test),
                                   batch_size=batch_size)

In [ ]:
dataloader_train

In [ ]:
from transformers import AdamW, get_linear_schedule_with_warmup

optimizer = AdamW(model.parameters(),
                  lr=1e-5,
                  eps=1e-8)

epochs = 5

scheduler = get_linear_schedule_with_warmup(optimizer,
                                            num_warmup_steps=0,
                                            num_training_steps=len(dataloader_train)*epochs)


/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
from sklearn.metrics import f1_score

def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average='weighted')

def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}

    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()

    for label in np.unique(labels_flat):
        y_preds = preds_flat[labels_flat==label]
        y_true = labels_flat[labels_flat==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy: {len(y_preds[y_preds==label])}/{len(y_true)}\n')

In [ ]:
torch.device

torch.device

In [ ]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [ ]:
def evaluate(dataloader_val):

    model.eval()

    loss_val_total = 0
    predictions, true_vals = [], []

    for batch in dataloader_val:

        batch = tuple(b for b in batch)

        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        with torch.no_grad():
            outputs = model(**inputs)

        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)

    loss_val_avg = loss_val_total/len(dataloader_val)

    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)

    return loss_val_avg, predictions, true_vals

In [ ]:
tqdm(20)

0it [00:00, ?it/s]

In [ ]:
progress_bar = tqdm(dataloader_train, desc='Epoch {:1d}'.format(10), leave=False, disable=False)

Epoch 10:   0%|          | 0/334 [00:00<?, ?it/s]

In [ ]:
progress_bar.to

AttributeError: ignored

In [ ]:
!mkdir data_volume/

In [ ]:
for epoch in tqdm(range(1, epochs+1)):

    model.train()

    loss_train_total = 0

    progress_bar = tqdm(dataloader_train, desc='Epoch {:1d}'.format(epoch), leave=False, disable=False)
    for batch in progress_bar:

        model.zero_grad()

        batch = tuple(b for b in batch)

        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        outputs = model(**inputs)

        loss = outputs[0]
        loss_train_total += loss.item()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})


    torch.save(model.state_dict(), f'data_volume/finetuned_BERT_epoch_{epoch}.model')

    tqdm.write(f'\nEpoch {epoch}')

    loss_train_avg = loss_train_total/len(dataloader_train)
    tqdm.write(f'Training loss: {loss_train_avg}')

    val_loss, predictions, true_vals = evaluate(dataloader_validation)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation loss: {val_loss}')
    tqdm.write(f'F1 Score (Weighted): {val_f1}')

  0%|          | 0/5 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/334 [00:00<?, ?it/s]


Epoch 1
Training loss: 2.1589979914847963
Validation loss: 1.918510516960464
F1 Score (Weighted): 0.36106846486950156


Epoch 2:   0%|          | 0/334 [00:00<?, ?it/s]


Epoch 2
Training loss: 1.684646109442511
Validation loss: 1.59580379938651
F1 Score (Weighted): 0.4054292812938895


Epoch 3:   0%|          | 0/334 [00:00<?, ?it/s]


Epoch 3
Training loss: 1.2688347639259463
Validation loss: 1.3576347620901232
F1 Score (Weighted): 0.5318227121292428


Epoch 4:   0%|          | 0/334 [00:00<?, ?it/s]


Epoch 4
Training loss: 0.9947980435754724
Validation loss: 1.32230348965365
F1 Score (Weighted): 0.5174602566046225


Epoch 5:   0%|          | 0/334 [00:00<?, ?it/s]


Epoch 5
Training loss: 0.8424757909542786
Validation loss: 1.2865332917360488
F1 Score (Weighted): 0.5429717465825179
