In [ ]:
!pip install datasets
!pip install Sastrawi

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.2/492.2 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 19.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.6 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from datasets import load_dataset

from google.colab import data_table

data_table.disable_dataframe_formatter()
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.multioutput import MultiOutputClassifier

from sklearn.model_selection import cross_val_score, KFold

import nltk
nltk.download('stopwords')
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pickle

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
DataPath = "/content/drive/MyDrive/Magang/ThreatDetection/Data/"

In [ ]:
dfAbusive = pd.read_csv(f"{DataPath}dfCatagory/dfAbusive.csv")
dfHS_Individual = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Individual.csv")
dfHS_Group = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Group.csv")
dfHS_Religion = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Religion.csv")
dfHS_Race = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Race.csv")
dfHS_Physical = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Physical.csv")
dfHS_Gender = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Gender.csv")
dfHS_Other = pd.read_csv(f"{DataPath}dfCatagory/dfHS_Other.csv")
dfsexual_orientation = pd.read_csv(f"{DataPath}dfCatagory/dfsexual_orientation.csv")
dfdisability = pd.read_csv(f"{DataPath}dfCatagory/dfdisability.csv")
dfnational_origin = pd.read_csv(f"{DataPath}dfCatagory/dfnational_origin.csv")
dfviolence  = pd.read_csv(f"{DataPath}dfCatagory/dfviolence.csv")


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
dfAbusive.drop(columns = "Unnamed: 0", inplace = True)

In [ ]:
dfHS_Individual.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Group.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Religion.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Race.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Physical.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Gender.drop(columns = "Unnamed: 0", inplace = True)
dfHS_Other.drop(columns = "Unnamed: 0", inplace = True)
dfsexual_orientation.drop(columns = "Unnamed: 0", inplace = True)
dfdisability.drop(columns = "Unnamed: 0", inplace = True)
dfnational_origin.drop(columns = "Unnamed: 0", inplace = True)
dfviolence.drop(columns = "Unnamed: 0", inplace = True)

In [ ]:

from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn import tree
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression



In [ ]:
# x_train,x_test,y_train,y_test = train_test_split(dfAbusive.iloc[:, :-1], dfAbusive.iloc[:, -1],test_size=0.3,random_state=101)

In [ ]:
scores = cross_val_score(svm, dfAbusive.iloc[:, :-1], dfAbusive.iloc[:, -1], cv=10)

In [ ]:
scores

array([0.84 , 0.817, 0.857, 0.846, 0.871, 0.851, 0.847, 0.838, 0.835,
       0.848])

In [ ]:
scores = cross_val_score(tree, dfAbusive.iloc[:, :-1], dfAbusive.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Group.iloc[:, :-1], dfHS_Group.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Religion.iloc[:, :-1], dfHS_Religion.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Race.iloc[:, :-1], dfHS_Race.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Physical.iloc[:, :-1], dfHS_Physical.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Gender.iloc[:, :-1], dfHS_Gender.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfHS_Other.iloc[:, :-1], dfHS_Other.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfsexual_orientation.iloc[:, :-1], dfsexual_orientation.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfdisability.iloc[:, :-1], dfdisability.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfnational_origin.iloc[:, :-1], dfnational_origin.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfviolence.iloc[:, :-1], dfviolence.iloc[:, -1], cv=10)

[0.77  0.777 0.814 0.798 0.815 0.807 0.8   0.8   0.778 0.804]
[0.712 0.715 0.712 0.724 0.701 0.694 0.694 0.721 0.818 0.799]
[0.781 0.76  0.765 0.779 0.77  0.83  0.848 0.819 0.846 0.839]
[0.911 0.925 0.95  0.941 0.947 0.93  0.943 0.938 0.939 0.949]
[0.94  0.948 0.95  0.954 0.948 0.958 0.953 0.964 0.95  0.955]
[0.892 0.905 0.901 0.925 0.913 0.907 0.901 0.916 0.91  0.915]
[0.899 0.933 0.914 0.913 0.913 0.912 0.921 0.909 0.92  0.903]
[0.748 0.77  0.738 0.722 0.756 0.769 0.737 0.773 0.777 0.779]
[0.932 0.939 0.948 0.94  0.949 0.938 0.935 0.926 0.945 0.944]
[0.931 0.949 0.957 0.935 0.937 0.934 0.949 0.949 0.938 0.939]
[0.973 0.971 0.973 0.975 0.98  0.98  0.976 0.98  0.979 0.976]


In [ ]:
scores = cross_val_score(svm, dfAbusive.iloc[:, :-1], dfAbusive.iloc[:, -1], cv=10)
print("Abusive:",scores)
scores = cross_val_score(svm, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print("HS individual",scores)
scores = cross_val_score(svm, dfHS_Group.iloc[:, :-1], dfHS_Group.iloc[:, -1], cv=10)
print("HS group", scores)

scores = cross_val_score(tree, dfHS_Religion.iloc[:, :-1], dfHS_Religion.iloc[:, -1], cv=10)
print("HS Religion",scores)
scores = cross_val_score(tree, dfHS_Race.iloc[:, :-1], dfHS_Race.iloc[:, -1], cv=10)
print("HS_Race",scores)
scores = cross_val_score(tree, dfHS_Physical.iloc[:, :-1], dfHS_Physical.iloc[:, -1], cv=10)
print("HS_Physical",scores)
scores = cross_val_score(tree, dfHS_Gender.iloc[:, :-1], dfHS_Gender.iloc[:, -1], cv=10)
print("HS_Gender",scores)

scores = cross_val_score(svm, dfHS_Other.iloc[:, :-1], dfHS_Other.iloc[:, -1], cv=10)
print("HS other",scores)

scores = cross_val_score(tree, dfsexual_orientation.iloc[:, :-1], dfsexual_orientation.iloc[:, -1], cv=10)
print("sexual_orientation",scores)
scores = cross_val_score(tree, dfdisability.iloc[:, :-1], dfdisability.iloc[:, -1], cv=10)
print("disability",scores)
scores = cross_val_score(tree, dfnational_origin.iloc[:, :-1], dfnational_origin.iloc[:, -1], cv=10)
print(scores)
scores = cross_val_score(tree, dfviolence.iloc[:, :-1], dfviolence.iloc[:, -1], cv=10)
print("violence",scores)


Abusive: [0.84  0.817 0.857 0.846 0.871 0.851 0.847 0.838 0.835 0.848]
HS individual [0.781 0.772 0.774 0.771 0.778 0.771 0.758 0.782 0.873 0.88 ]
HS group [0.791 0.794 0.8   0.811 0.83  0.943 0.947 0.939 0.939 0.944]
HS Religion [0.908 0.918 0.95  0.939 0.946 0.927 0.945 0.942 0.941 0.948]
HS_Race [0.938 0.945 0.953 0.959 0.942 0.955 0.955 0.96  0.947 0.955]
HS_Physical [0.891 0.908 0.899 0.921 0.912 0.905 0.905 0.917 0.911 0.914]
HS_Gender [0.899 0.931 0.914 0.918 0.909 0.913 0.92  0.907 0.924 0.908]
HS other [0.799 0.804 0.805 0.776 0.793 0.818 0.794 0.853 0.894 0.907]
sexual_orientation [0.934 0.943 0.946 0.941 0.949 0.937 0.935 0.934 0.946 0.942]
disability [0.928 0.949 0.96  0.935 0.93  0.937 0.952 0.949 0.93  0.946]
[0.976 0.97  0.973 0.977 0.98  0.98  0.98  0.978 0.972 0.974]
violence [0.962 0.956 0.968 0.961 0.96  0.97  0.959 0.956 0.949 0.96 ]


In [ ]:
scores = cross_val_score(Rnf, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print("HS individual",scores)
scores = cross_val_score(Rnf, dfHS_Group.iloc[:, :-1], dfHS_Group.iloc[:, -1], cv=10)
print("HS group", scores)
scores = cross_val_score(Rnf, dfHS_Other.iloc[:, :-1], dfHS_Other.iloc[:, -1], cv=10)
print("HS other",scores)


HS individual [0.764 0.759 0.744 0.766 0.771 0.741 0.73  0.753 0.84  0.843]
HS group [0.836 0.825 0.833 0.817 0.827 0.855 0.866 0.848 0.856 0.863]
HS other [0.781 0.799 0.784 0.768 0.801 0.803 0.792 0.807 0.818 0.833]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
Gbst = GradientBoostingClassifier()

In [ ]:
scores = cross_val_score(Gbst, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print("HS individual",scores)
scores = cross_val_score(Gbst, dfHS_Other.iloc[:, :-1], dfHS_Other.iloc[:, -1], cv=10)
print("HS other",scores)

HS individual [0.695 0.716 0.693 0.701 0.704 0.693 0.671 0.647 0.696 0.703]
HS other [0.735 0.738 0.742 0.715 0.736 0.721 0.721 0.731 0.731 0.75 ]


In [ ]:
scores = cross_val_score(logistic, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print("HS individual",scores)
scores = cross_val_score(logistic, dfHS_Other.iloc[:, :-1], dfHS_Other.iloc[:, -1], cv=10)
print("HS other",scores)

HS individual [0.771 0.754 0.771 0.764 0.751 0.745 0.738 0.721 0.801 0.794]
HS other [0.805 0.802 0.793 0.779 0.785 0.81  0.78  0.819 0.782 0.788]


In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
SGD = SGDClassifier()

In [ ]:
scores = cross_val_score(SGD, dfHS_Individual.iloc[:, :-1], dfHS_Individual.iloc[:, -1], cv=10)
print("HS individual",scores)

HS individual [0.758 0.754 0.751 0.765 0.735 0.73  0.737 0.743 0.801 0.811]


In [ ]:
Rnf = RandomForestClassifier()
svm = SVC()
tree = tree.DecisionTreeClassifier()
logistic = LogisticRegression()

In [ ]:
scores = cross_val_score(svm, dfAbusive.iloc[:, :-1].values, dfAbusive.iloc[:, -1].values, cv=10)
print("Abusive:",scores)
scores = cross_val_score(svm, dfHS_Individual.iloc[:, :-1].values, dfHS_Individual.iloc[:, -1].values, cv=10)
print("HS individual",scores)
scores = cross_val_score(Rnf, dfHS_Group.iloc[:, :-1].values, dfHS_Group.iloc[:, -1].values, cv=10)
print("HS group", scores)


scores = cross_val_score(tree, dfHS_Religion.iloc[:, :-1].values, dfHS_Religion.iloc[:, -1].values, cv=10)
print("HS Religion",scores)
scores = cross_val_score(tree, dfHS_Race.iloc[:, :-1].values, dfHS_Race.iloc[:, -1].values, cv=10)
print("HS_Race",scores)
scores = cross_val_score(tree, dfHS_Physical.iloc[:, :-1].values, dfHS_Physical.iloc[:, -1].values, cv=10)
print("HS_Physical",scores)
scores = cross_val_score(tree, dfHS_Gender.iloc[:, :-1].values, dfHS_Gender.iloc[:, -1].values, cv=10)
print("HS_Gender",scores)

scores = cross_val_score(logistic, dfHS_Other.iloc[:, :-1].values, dfHS_Other.iloc[:, -1].values, cv=10)
print("HS other",scores)

scores = cross_val_score(tree, dfsexual_orientation.iloc[:, :-1].values, dfsexual_orientation.iloc[:, -1].values, cv=10)
print("sexual_orientation",scores)
scores = cross_val_score(tree, dfdisability.iloc[:, :-1].values, dfdisability.iloc[:, -1].values, cv=10)
print("disability",scores)
scores = cross_val_score(tree, dfnational_origin.iloc[:, :-1].values, dfnational_origin.iloc[:, -1].values, cv=10)
print(scores)
scores = cross_val_score(tree, dfviolence.iloc[:, :-1].values, dfviolence.iloc[:, -1].values, cv=10)
print("violence",scores)

Abusive: [0.84  0.817 0.857 0.846 0.871 0.851 0.847 0.838 0.835 0.848]
HS individual [0.781 0.772 0.774 0.771 0.778 0.771 0.758 0.782 0.873 0.88 ]
HS group [0.829 0.827 0.833 0.832 0.819 0.854 0.858 0.85  0.854 0.871]
HS Religion [0.914 0.927 0.949 0.941 0.946 0.928 0.947 0.938 0.942 0.949]
HS_Race [0.937 0.95  0.952 0.955 0.949 0.955 0.958 0.964 0.944 0.956]
HS_Physical [0.89  0.911 0.904 0.927 0.908 0.913 0.909 0.917 0.91  0.914]
HS_Gender [0.891 0.929 0.914 0.918 0.911 0.91  0.918 0.91  0.925 0.904]
HS other [0.805 0.802 0.793 0.779 0.785 0.81  0.78  0.819 0.782 0.788]
sexual_orientation [0.926 0.942 0.949 0.937 0.947 0.941 0.933 0.933 0.942 0.942]
disability [0.925 0.944 0.953 0.936 0.935 0.937 0.95  0.944 0.933 0.947]
[0.975 0.97  0.975 0.976 0.978 0.981 0.98  0.982 0.979 0.977]
violence [0.961 0.957 0.967 0.96  0.959 0.976 0.957 0.953 0.949 0.962]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
import sklearn

In [ ]:
print(sklearn.__version__)

1.3.0


In [ ]:
!pip install scikit-learn==1.3.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 42.9 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [ ]:
AbusiveModel = SVC()
HS_IndividualModel = SVC()
HS_GroupModel = RandomForestClassifier()
HS_ReligionModel = DecisionTreeClassifier()
HS_RaceModel = DecisionTreeClassifier()
HS_PhysicalModel = DecisionTreeClassifier()
HS_GenderModel = DecisionTreeClassifier()
HS_OtherModel = LogisticRegression()
sexual_orientationModel = DecisionTreeClassifier()
disabilityModel = DecisionTreeClassifier()
national_originModel = DecisionTreeClassifier()
violenceModel = DecisionTreeClassifier()


In [ ]:
dfAbusive

abang  abis  abu  acara  ada  adab  adat  ade  adek  adem  ...  yahudi  \
0       0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
1       0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
2       0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
3       0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
4       0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
...     ...   ...  ...    ...  ...   ...   ...  ...   ...   ...  ...     ...   
9995    0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
9996    0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
9997    0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
9998    0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   
9999    0.0   0.0  0.0    0.0  0.0   0.0   0.0  0.0   0.0   0.0  ...     0.0   

      yakin  yaudah   ye  you  zalim  zaman  zionis  zonk  Abusive  
0       0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        0  
1       0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        0  
2       0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        0  
3       0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        0  
4       0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        0  
...     ...     ...  ...  ...    ...    ...     ...   ...      ...  
9995    0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        1  
9996    0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        1  
9997    0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        1  
9998    0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        1  
9999    0.0     0.0  0.0  0.0    0.0    0.0     0.0   0.0        1  

[10000 rows x 1706 columns]

In [ ]:
AbusiveModel.fit(dfAbusive.iloc[:, :-1].values, dfAbusive.iloc[:, -1].values)
HS_IndividualModel.fit(dfHS_Individual.iloc[:, :-1].values, dfHS_Individual.iloc[:, -1].values)
HS_GroupModel.fit(dfHS_Group.iloc[:, :-1].values, dfHS_Group.iloc[:, -1].values)
HS_ReligionModel.fit(dfHS_Religion.iloc[:, :-1].values, dfHS_Religion.iloc[:, -1].values)
HS_RaceModel.fit(dfHS_Race.iloc[:, :-1].values, dfHS_Race.iloc[:, -1].values)
HS_PhysicalModel.fit(dfHS_Physical.iloc[:, :-1].values, dfHS_Physical.iloc[:, -1].values)
HS_GenderModel.fit(dfHS_Gender.iloc[:, :-1].values, dfHS_Gender.iloc[:, -1].values)
HS_OtherModel.fit(dfHS_Other.iloc[:, :-1].values, dfHS_Other.iloc[:, -1].values)
sexual_orientationModel.fit(dfsexual_orientation.iloc[:, :-1].values, dfsexual_orientation.iloc[:, -1].values)
disabilityModel.fit(dfdisability.iloc[:, :-1].values, dfdisability.iloc[:, -1].values)
national_originModel.fit(dfnational_origin.iloc[:, :-1].values, dfnational_origin.iloc[:, -1].values)
violenceModel.fit(dfviolence.iloc[:, :-1].values, dfviolence.iloc[:, -1].values)

DecisionTreeClassifier()

In [ ]:
type(HS_RaceModel)

sklearn.tree._classes.DecisionTreeClassifier

In [ ]:
with open('AbusiveModel.pkl', 'wb') as file:
    pickle.dump(AbusiveModel, file)

with open('HS_IndividualModel.pkl', 'wb') as file:
    pickle.dump(HS_IndividualModel, file)

with open('HS_GroupModel.pkl', 'wb') as file:
    pickle.dump(HS_GroupModel, file)

with open('HS_ReligionModel.pkl', 'wb') as file:
    pickle.dump(HS_ReligionModel, file)

with open('HS_RaceModel.pkl', 'wb') as file:
    pickle.dump(HS_RaceModel, file)

with open('HS_PhysicalModel.pkl', 'wb') as file:
    pickle.dump(HS_PhysicalModel, file)

with open('HS_GenderModel.pkl', 'wb') as file:
    pickle.dump(HS_GenderModel, file)

with open('HS_OtherModel.pkl', 'wb') as file:
    pickle.dump(HS_OtherModel, file)

with open('sexual_orientationModel.pkl', 'wb') as file:
    pickle.dump(sexual_orientationModel, file)

with open('disabilityModel.pkl', 'wb') as file:
    pickle.dump(disabilityModel, file)

with open('national_originModel.pkl', 'wb') as file:
    pickle.dump(national_originModel, file)

with open('violenceModel.pkl', 'wb') as file:
    pickle.dump(violenceModel, file)



In [ ]:
def preprocess(sentence:list):
  # case Folding
  sentences = [sentence.lower() for sentence in sentence]
  # print(sentences)


  # tokenizer
  tokenizer     = RegexpTokenizer(r'(?<!\S)[A-Za-z]+(?!\S)|(?<!\S)[A-Za-z]+(?=:(?!\S))')
  # hasil_token   = tokenizer.tokenize(sentences[1])
  token_sentence = [tokenizer.tokenize(sentence) for sentence in sentences]
  # print(token_sentence)


  # ah, al, ala, an, and, as, atau, awal, be, ber, bin, bro, bu, bung, but, by, cak, cc, dan, deh, dengan, di, dil, dong, dua, eh, fadli, fahri
  # fan, for, front, full, harto, hasan, he, hehe, hem, ia, ih, in, is, itu, iya, je, juga, kah, kak, kan, kang, kat, "kau", ke, km, kok, ku, ky
  # lah, like, lima, live, "lo", me, mei, men, min, mk, mu, my, nah, nak, namun, nek, nih, no, nya, of, oh, oi, oke, -pada, pak, per, ppp, pun, ra
  # rang, rt, sa, se, seba, si, sing, ta, tang, tar, tau, the, ting, to, toh, tomohon, uniform, up, untuk, user, wah, wkwk, ya, yaitu, yakni, yang, zon

  # yuk,yg,yaa,wkwkwk,tdk,so,kyk,ko,jg,jgn,jd,jdi,hrs,haha,gw,gk,ga,ente,emg,elo,dr,dlm,dgn,byk,bkn,aq,ama,aku,adlh,ad

  # ad,adlh,aku,ama,aq,bgt,bkn,blg,bnyk,bs,byk,da,dah,dapet,dapat,dengar,dg,dgn,dll,ga,gmn,gt,gw,haha,hahaha,jd,jdi,jgn,ka,karna,ken,kl,klo,kyk,lg,lho,lu,mmg,mo,msh,ngga,nggak,ntar,yg,yo
  words = """ad,adlh,aku,ama,aq,bgt,bkn,blg,bnyk,bs,byk,da,dah,dapet,dapat,dengar,dg,dgn,dll,ga,gmn,gt,gw,haha,hahaha,jd,jdi,jgn,ka,karna,ken,kl,klo,kyk,lg,lho,lu,mmg,mo,msh,ngga,nggak,ntar,yg,yo,yuk,yg,yaa,wkwkwk,tdk,so,kyk,ko,jg,jgn,jd,jdi,hrs,haha,gw,gk,ga,ente,emg,elo,dr,dlm,dgn,byk,bkn,aq,ama,aku,adlh,ad,gue,aja,aku,pengguna,ah,al,ala,an,and,as,atau,awal,be,ber,bin,bro,bu,bung,but,by,cak,cc,dan,deh,dengan,di,dil,dong,dua,eh,fadli,fahri,fan,for,front,full,harto,hasan,he,hehe,hem,ia,ih,in,is,itu,iya,je,juga,kah,kak,kan,kang,kat,kau,ke,km,kok,ku,ky,lah,like,lima,live,lo,me,mei,men,min,mk,mu,my,nah,nak,namun,nek,nih,no,nya,of,oh,oi,oke,pak,per,ppp,pun,ra,rang,rt,sa,se,seba,si,sing,ta,tang,tar,ter,tau,the,ting,to,toh,tomohon,uniform,up,untuk,user,wah,wkwk,ya,yaitu,yakni,yang,zon"""
  word = words.split(",")
  # word = np.reshape(word, -1)
  # word.tolist()
  # stopword
  wordlist= set(stopwords.words('indonesian') + word)
  sw_sentences = [[word for word in sentence if word not in wordlist]for sentence in token_sentence]
  cleaned_sentences = [' '.join(sentence) for sentence in sw_sentences]
  # print(cleaned_sentences)


  #[str(sentence) for sentence in sw_sentences]
  # stemming
  stemmer     = StemmerFactory().create_stemmer()
  # input_stemm   = str(sw_sentences)
  # hasil_stemm   = stemmer.stem(input_stemm)
  # print (hasil_stemm)
  stem_sentence = [stemmer.stem(sentence) for sentence in cleaned_sentences]
  # print(stem_sentence)
  return stem_sentence

In [ ]:
with open(fr'fitted_vectorizer.pkl', 'rb') as file:
    vectorizer = pickle.load(file)

In [ ]:
kalimat = preprocess(["Mereka harus dibunuh secepat mungkin"])

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 32.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.4 MB/s eta 0:00:00


In [ ]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
def model_bert(kalimat):
    pretrained = "mdhugol/indonesia-bert-sentiment-classification"

    sentiment_analysis = pipeline(
        "sentiment-analysis",
        model=AutoModelForSequenceClassification.from_pretrained(pretrained),
        tokenizer=AutoTokenizer.from_pretrained(pretrained)
    )

    sentiment = sentiment_analysis(kalimat)
    label_index = {'LABEL_0': 'positive',
                   'LABEL_1': 'neutral', 'LABEL_2': 'negative'}
    score = sentiment[0]['score']
    sentiment = {
        'label': f"{label_index[sentiment[0]['label']]}", 'score': f"{score}"}
    return sentiment

In [ ]:
model_bert("Bagus banget")

{'label': 'positive', 'score': '0.9969387054443359'}

In [ ]:
model_bert("Mereka harus dibunuh secepat mungkin")['label'] == 'negative'

True

In [ ]:
kalimat[0]

'bunuh cepat'

In [ ]:
if model_bert("Mereka harus dibunuh secepat mungkin")['label'] == 'negative'

In [ ]:
x_trans = vectorizer.transform(kalimat)
# feature_names = vectorizer.get_feature_names_out()
# array = x_trans.toarray()
# arraylist = array.tolist()


In [ ]:
Abusive_pred = AbusiveModel.predict(vectorizer.transform(kalimat).toarray())
HS_IndividualModel = HS_IndividualModel.predict(vectorizer.transform(kalimat).toarray())
HS_GroupModel = HS_GroupModel.predict(vectorizer.transform(kalimat).toarray())
HS_ReligionModel = HS_ReligionModel.predict(vectorizer.transform(kalimat).toarray())
HS_RaceModel = HS_RaceModel.predict(vectorizer.transform(kalimat).toarray())
HS_PhysicalModel = HS_PhysicalModel.predict(vectorizer.transform(kalimat).toarray())
HS_GenderModel = HS_GenderModel.predict(vectorizer.transform(kalimat).toarray())
HS_OtherModel = HS_OtherModel.predict(vectorizer.transform(kalimat).toarray())
sexual_orientationModel = sexual_orientationModel.predict(vectorizer.transform(kalimat).toarray())
disabilityModel = disabilityModel.predict(vectorizer.transform(kalimat).toarray())
national_originModel = national_originModel.predict(vectorizer.transform(kalimat).toarray())
violenceModel = violenceModel.predict(vectorizer.transform(kalimat).toarray())

In [ ]:
tes = [2]

In [ ]:
not tes

False

In [ ]:
y_pred_combined = np.column_stack((Abusive_pred, HS_IndividualModel, HS_GroupModel, HS_ReligionModel, HS_RaceModel, HS_PhysicalModel, HS_GenderModel, HS_OtherModel, sexual_orientationModel, disabilityModel, national_originModel, violenceModel))

In [ ]:
y_pred_combined

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [ ]:
violenceModel.predict(vectorizer.transform(kalimat).toarray())

In [ ]:
kalimat

['bunuh cepat']

In [ ]:
# Combine the predictions
y_pred_combined = np.column_stack((y_pred1, y_pred2, y_pred3, y_pred4, y_pred5))