In [ ]:
!pip install Sastrawi
!pip install sklearn-crfsuite

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 993.5/993.5 kB 20.9 MB/s eta 0:00:00


In [ ]:
text = "Presiden PKS Respons Peluang Ganjar dan Anies Duet di Pilpres 2024"

In [ ]:
# Use a pipeline as a high-level helper
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import nltk
nltk.download('stopwords')
import pandas as pd
import random

from transformers import pipeline
from nltk.tag import CRFTagger
import pycrfsuite

pipe = pipeline("token-classification", model="w11wo/indonesian-roberta-base-posp-tagger")

pipe_NER = pipeline("token-classification", model="ageng-anugrah/indobert-large-p2-finetuned-ner")


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
pipe_NER(text)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


[{'entity': 'B-ORGANISATION',
  'score': 0.9947108,
  'index': 2,
  'word': 'pks',
  'start': 9,
  'end': 12},
 {'entity': 'B-PERSON',
  'score': 0.9998534,
  'index': 5,
  'word': 'ganja',
  'start': 29,
  'end': 34},
 {'entity': 'I-PERSON',
  'score': 0.50826854,
  'index': 6,
  'word': '##r',
  'start': 34,
  'end': 35},
 {'entity': 'B-PERSON',
  'score': 0.99791354,
  'index': 8,
  'word': 'anies',
  'start': 40,
  'end': 45}]

In [ ]:
pipe(text)

In [ ]:
print(text)
POS = pipe(text)
POS
POS[2]['entity']

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Presiden PKS Respons Peluang Ganjar dan Anies Duet di Pilpres 2024


'B-NNO'

In [ ]:
[i['word'] for i in POS if i['entity']=='B-NNO']

['ĠPresiden', 'ĠPKS', 'ĠRespons', 'ĠPeluang', 'ĠDu', 'et', 'ĠPilpres']

In [ ]:
def prerocessing_indo(sentences):
    # case Folding
    sentences = [sentence.lower() for sentence in sentences]

    # tokenizer
    tokenizer     = RegexpTokenizer(r'(?<!\S)[A-Za-z]+(?!\S)|(?<!\S)[A-Za-z]+(?=:(?!\S))')
    # hasil_token   = tokenizer.tokenize(sentences[1])
    token_sentence = [tokenizer.tokenize(sentence) for sentence in sentences]

    # stopword

    wordlist= set(stopwords.words('indonesian')+["all", "halaman", "off", "mengunggah file"]+ stopwords.words('english'))
    sw_sentences = [[word for word in sentence if word not in wordlist]for sentence in token_sentence]
    cleaned_sentences = [' '.join(sentence) for sentence in sw_sentences]

    #[str(sentence) for sentence in sw_sentences]
    # stemming
    stemmer     = StemmerFactory().create_stemmer()
    # input_stemm   = str(sw_sentences)
    # hasil_stemm   = stemmer.stem(input_stemm)
    # print (hasil_stemm)
    stem_sentence = [stemmer.stem(sentence) for sentence in cleaned_sentences]
    sentence =  stem_sentence
    return sentence

In [ ]:
news = pd.read_csv("news.csv", on_bad_lines='skip', header= None)

list_news = news.iloc[:,-1].values.tolist()
random.shuffle(list_news)
doc = prerocessing_indo(list_news)
# doc = [i for i in doc if i]
doc

['binaragawan justyn vicky vcall tewas tertimpa barbel',
 'style mamba ala idol idol elegan mengenakan pakaian berwarna hitam',
 'larangan mencegah wajib berjilbab sekolah memupus intoleransi',
 'juventus',
 'barcelona bidik pelatih sassuolo gantikan ernesto',
 'rafael leao milan rumah',
 'mengulas khilafatul muslimin dianggap melanggar uu ormas',
 'menyebabkan munculnya jerawat dagu cantik',
 'kronologi aksi koboi pria wanita karyawan salon',
 'aliansi asia pasifik dukung pertumbuhan ekonomi digital nasional',
 'rhinitis kenali gejala penyebabnya gaya',
 'foto drama kemenangan alex rins suzuki motogp australia',
 'george clooney berita terbaru',
 'wuling kerahkan unit kendaraan listrik ktt asean tantrum',
 'jaenal aripin menangis raih medali perak nomor kursi roda meter putra',
 'klasemen liga laga psm makassar vs persib bandung',
 'sejarah maskapai sriwijaya air jenis pesawat dioperasikan',
 'link live streaming liverpool vs aston villa',
 'menteri bumn lapor presiden juta kaum milen

In [ ]:
stem_corpus = prerocessing_indo(list_news[20:60])

In [ ]:
list_news[20:40]

['Melihat Kampung Pembuat Kerupuk Mie di Karadenan - Foto 1',
 'Lirik Lagu dan Terjemahan Bahasa Indonesia Cola - Lana Del Rey: We Can Escape To The Great Sunshine -  Halaman all -   ',
 'Ini Alasan Tony Leung Tak Pernah Main di Film Stephen Chow',
 'Oppo Reno 10x Zoom Jadi Solusi Kamera DSLR yang Bikin Risih',
 'Maserati GT2 Hadir di Ajang 24 Hours of Spa-Francorchamps - Otomotif ',
 'Polisi Masih Belum Temukan Singa yang Berkeliaran di Berlin',
 'Wawancara Raja Sapta Oktohari: Jadi Pengusaha Itu Privilegenya Dapat Keleluasaan (Part 3-Habis) - ',
 'LBH Surabaya Soroti Peradilan Militer di Draf Revisi UU TNI',
 'Istana Jelaskan Maksud Jokowi akan Cawe-cawe di Pemilu 2024',
 'Momen Kocak Celana Pendek Lionel Messi Dicuri Usai Debut Manis Bersama Inter Miami : Okezone Bola',
 'VIDEO: Dua Aktivis Lempar Sup Tomat ke Lukisan Van Gogh Jutaan Dolar',
 'Piala Thomas 2022: Herry IP Rahasiakan Komposisi Ganda Putra Jelang Hadapi Korsel - ',
 'Susi Pudjiastuti Dorong Uni Emirat Arab Juga Larang 

In [ ]:
stem_corpus

['kampung buat kerupuk mie karadenan foto',
 'lirik lagu terjemah bahasa indonesia cola lana del rey escape great sunshine',
 'alas tony leung main film stephen chow',
 'oppo reno zoom solusi kamera dslr bikin risih',
 'maserati hadir ajang hours otomotif',
 'polisi temu singa liar lin',
 'wawancara raja sapta oktohari usaha privilegenya leluasa',
 'lbh surabaya sorot adil militer draf revisi uu tni',
 'istana maksud jokowi milu',
 'momen kocak celana pendek lionel messi curi debut manis inter miami okezone bola',
 'video aktivis lempar sup tomat lukis van gogh juta dolar',
 'piala thomas herry ip rahasia komposisi ganda putra jelang hadap korsel',
 'sus pudjiastuti dorong uni emirat arab larang transshipment bisnis',
 'marc marquez lupa pekan sulit sachsenring',
 'kh hasyim gulat diri nahdlatul ulama nasional',
 'kpk sita uang tunai ott jakarta bekas',
 'menu buka puasa favorit juta umat bandung',
 'klasemen liga pekan dewa utd pepet madura utd sita',
 'ribu investasi ilegal sikat ojk

In [ ]:
ct = CRFTagger()
ct.set_model_file('all_indo_man_tag_corpus_model.crf.tagger')

In [ ]:
test_text = doc[50]

print(test_text)
POS = pipe(test_text)
NER = pipe_NER(test_text)
print("-"*20)
print([i['word'] for i in POS if i['entity']=='B-NNO'])
print([[i['word'], i['entity']] for i in NER])

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


finland becomes happiest country sixth time
--------------------
[]
[['fin', 'B-PLACE'], ['##land', 'I-PLACE']]


In [ ]:
test_text = doc[1000]
print(test_text)
POS = pipe(test_text)
NER = pipe_NER(test_text)
print("-"*20)
print([i['word'] for i in POS if i['entity']=='B-NNO'])
print([[i['word'], i['entity']] for i in NER])

bakal ada armada blue bird di stasiun kereta cepat
--------------------
['Ġarmada', 'Ġstasiun', 'Ġkereta']
[['blue', 'B-ORGANISATION'], ['bird', 'I-ORGANISATION'], ['kereta', 'I-PLACE'], ['cepat', 'I-PLACE']]


In [ ]:
test_text = doc[200]
POS = pipe(test_text)
hasil_POS = [i['word'].replace("Ġ","") for i in POS if (i['entity']=='B-NNO') | (i['entity']=='B-NNP')]
hasil_NER = ct.tag_sents([hasil_POS])
hasil = [i[0] for i in hasil_NER[0] if i[1] != 'VB']

print(test_text)
print("*"*60)
print(hasil_POS)
print(hasil_NER)
print(hasil)

politik masjid pilkada dki yang meretakkan keluarga
************************************************************
['politik', 'masjid', 'pilkada', 'd', 'ki', 'keluarga']
[[('politik', 'NN'), ('masjid', 'NN'), ('pilkada', 'IN'), ('d', 'NN'), ('ki', 'NN'), ('keluarga', 'NN')]]
['politik', 'masjid', 'pilkada', 'd', 'ki', 'keluarga']


In [ ]:
hasil_NER = ct.tag_sents([doc[200].split(" ")])
hasil_NER

[[('politik', 'NN'),
  ('masjid', 'NN'),
  ('pilkada', 'IN'),
  ('dki', 'NN'),
  ('yang', 'SC'),
  ('meretakkan', 'VB'),
  ('keluarga', 'NN')]]

In [ ]:
for i in range(20, 40):
  test_text = doc[i]
  # POS = pipe(test_text)
  # hasil_POS = [i['word'].replace("Ġ","") for i in POS if (i['entity']=='B-NNO') | (i['entity']=='B-NNP')]
  hasil_NER = ct.tag_sents([test_text.split(" ")])
  hasil = [i[0] for i in hasil_NER[0] if i[1] == 'NN']

  print("#"*60)
  print(test_text)
  # print(hasil_POS)
  print(f"acuan : {hasil_NER}")
  print(f"topic : {hasil}\n")

############################################################
panglima tni pimpin sertijab ksal laksmana tni siwi sukma adji
acuan : [[('panglima', 'CD'), ('tni', 'NN'), ('pimpin', 'NN'), ('sertijab', 'NN'), ('ksal', 'NN'), ('laksmana', 'NN'), ('tni', 'PR'), ('siwi', 'VB'), ('sukma', 'NN'), ('adji', 'VB')]]
topic : ['tni', 'pimpin', 'sertijab', 'ksal', 'laksmana', 'sukma']

############################################################
mengintip kampung madinah di pesantren al fatah magetan foto
acuan : [[('mengintip', 'VB'), ('kampung', 'NN'), ('madinah', 'NN'), ('di', 'IN'), ('pesantren', 'NN'), ('al', 'NN'), ('fatah', 'NN'), ('magetan', 'NN'), ('foto', 'NN')]]
topic : ['kampung', 'madinah', 'pesantren', 'al', 'fatah', 'magetan', 'foto']

############################################################
harlah pkb jadi ajang konsolidasi akbar jelang pemilu nasional
acuan : [[('harlah', 'NN'), ('pkb', 'NN'), ('jadi', 'VB'), ('ajang', 'NN'), ('konsolidasi', 'NN'), ('akbar', 'NN'), ('jelang', '

In [ ]:
for i in range(len(stem_corpus)):
  test_text = stem_corpus[i]
  # POS = pipe(test_text)
  # hasil_POS = [i['word'].replace("Ġ","") for i in POS if (i['entity']=='B-NNO') | (i['entity']=='B-NNP')]
  hasil_NER = ct.tag_sents([test_text.split(" ")])
  hasil = [i[0] for i in hasil_NER[0] if i[1] == 'NN']

  if "jokowi" in test_text:
    hasil.append('jokowi')


  print("#"*60)
  # print(f"kalimat Asli : {list_news[20:40][0]}")
  print(test_text)
  # print(hasil_POS)
  print(f"acuan : {hasil_NER}")

  print(f"topic : {hasil}\n")


############################################################
panglima tni pimpin sertijab ksal laksmana tni siwi sukma adji
acuan : [[('panglima', 'CD'), ('tni', 'NN'), ('pimpin', 'NN'), ('sertijab', 'NN'), ('ksal', 'NN'), ('laksmana', 'NN'), ('tni', 'PR'), ('siwi', 'VB'), ('sukma', 'NN'), ('adji', 'VB')]]
topic : ['tni', 'pimpin', 'sertijab', 'ksal', 'laksmana', 'sukma']

############################################################
intip kampung madinah pesantren al fatah magetan foto
acuan : [[('intip', 'VB'), ('kampung', 'NN'), ('madinah', 'NN'), ('pesantren', 'NN'), ('al', 'NN'), ('fatah', 'NN'), ('magetan', 'NN'), ('foto', 'NN')]]
topic : ['kampung', 'madinah', 'pesantren', 'al', 'fatah', 'magetan', 'foto']

############################################################
harlah pkb ajang konsolidasi akbar jelang milu nasional
acuan : [[('harlah', 'NN'), ('pkb', 'NN'), ('ajang', 'NN'), ('konsolidasi', 'NN'), ('akbar', 'NN'), ('jelang', 'NN'), ('milu', 'NN'), ('nasional', 'JJ')]]
topic

# Experiment 2

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 32.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.2 MB/s eta 0:00:00


In [ ]:
# Use a pipeline as a high-level helper
from transformers import BertTokenizer, BertModel#, pipeline

# pipe = pipeline("token-classification", model="cahya/bert-base-indonesian-NER")
model_name='cahya/bert-base-indonesian-522M'
tokenizer = BertTokenizer.from_pretrained(model_name)

In [ ]:
tokenizer.encode("Silakan diganti dengan text apa saja.")

[3, 23629, 1507, 6407, 1555, 16376, 3397, 2957, 17, 1]

In [ ]:
tokenizer(text, return_tensors='tf')["pooled_output"]

KeyError: ignored

In [ ]:
# # Use a pipeline as a high-level helper
# from transformers import pipeline

# pipe = pipeline("automatic-speech-recognition", model="cahya/wav2vec2-large-xlsr-indonesian")

In [ ]:
import gensim

path = 'idwiki_word2vec_300.model'
id_w2v = gensim.models.word2vec.Word2Vec.load(path)


[('rajanya', 0.6927156448364258), ('kerajaan', 0.6887479424476624), ('penguasa', 0.6561841368675232), ('maharaja', 0.635337769985199), ('firaun', 0.6156154274940491), ('kertanagara', 0.6069247126579285), ('purnawarman', 0.6000310778617859), ('ratu', 0.5888345241546631), ('permaisuri', 0.5711089372634888), ('takhta', 0.5686213374137878)]


In [ ]:
print(id_w2v.wv.most_similar('raja'))

[('rajanya', 0.6927156448364258), ('kerajaan', 0.6887479424476624), ('penguasa', 0.6561841368675232), ('maharaja', 0.635337769985199), ('firaun', 0.6156154274940491), ('kertanagara', 0.6069247126579285), ('purnawarman', 0.6000310778617859), ('ratu', 0.5888345241546631), ('permaisuri', 0.5711089372634888), ('takhta', 0.5686213374137878)]


In [ ]:
doc[20:40]

In [ ]:
compare_data =[
    ['lirik', 'lagu'],
    ['bahasa', 'indonesia'],
    ['tanda', 'pesawat'],
    ['bangun', 'rumah'],
    ['malaysia', 'indonesia'],
    ['raja', 'kerajaan'],
    ['saya', 'aku'],
    ['islam', 'masjid'],
    ['masjid', 'muhammadiyah'],
    ['laptop', 'acer']
]

In [ ]:
for banding in compare_data:
  print(f"{banding[0]} : {banding[1]} => ", id_w2v.wv.similarity(banding[0], banding[1]))


lirik : lagu =>  0.6363407
bahasa : indonesia =>  0.08925351
tanda : pesawat =>  0.18004549
bangun : rumah =>  0.19958022
malaysia : indonesia =>  0.468896
raja : kerajaan =>  0.68874794
saya : aku =>  0.7187076
islam : masjid =>  0.42872092
masjid : muhammadiyah =>  0.2959891
laptop : acer =>  0.34668463


In [ ]:
print(f"lirik : lagu => {id_w2v.wv.similarity('lirik', 'lagu')}")
print(f'bahasa : indonesia => {id_w2v.wv.similarity("bahasa", "indonesia")}')

lirik : lagu => 0.6363406777381897
bahasa : indonesia => 0.0892535075545311


In [ ]:
# from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
stem_corpus

['kampung buat kerupuk mie karadenan foto',
 'lirik lagu terjemah bahasa indonesia cola lana del rey escape great sunshine',
 'alas tony leung main film stephen chow',
 'oppo reno zoom solusi kamera dslr bikin risih',
 'maserati hadir ajang hours otomotif',
 'polisi temu singa liar lin',
 'wawancara raja sapta oktohari usaha privilegenya leluasa',
 'lbh surabaya sorot adil militer draf revisi uu tni',
 'istana maksud jokowi milu',
 'momen kocak celana pendek lionel messi curi debut manis inter miami okezone bola',
 'video aktivis lempar sup tomat lukis van gogh juta dolar',
 'piala thomas herry ip rahasia komposisi ganda putra jelang hadap korsel',
 'sus pudjiastuti dorong uni emirat arab larang transshipment bisnis',
 'marc marquez lupa pekan sulit sachsenring',
 'kh hasyim gulat diri nahdlatul ulama nasional',
 'kpk sita uang tunai ott jakarta bekas',
 'menu buka puasa favorit juta umat bandung',
 'klasemen liga pekan dewa utd pepet madura utd sita',
 'ribu investasi ilegal sikat ojk

In [ ]:
import nltk
nltk.download("averaged_perceptron_tagger")
nltk.download("punkt")

[nltk_data] Error loading
[nltk_data]     https://raw.githubusercontent.com/nltk/nltk_data/gh-
[nltk_data]     pages/packages/corpora/omw.zip: Package
[nltk_data]     'https://raw.githubusercontent.com/nltk/nltk_data/gh-
[nltk_data]     pages/packages/corpora/omw.zip' not found in index


False

In [ ]:
from nltk import pos_tag, word_tokenize

In [ ]:
pos_tag(word_tokenize("John's big idea isn't all that bad."))

[('John', 'NNP'),
 ("'s", 'POS'),
 ('big', 'JJ'),
 ('idea', 'NN'),
 ('is', 'VBZ'),
 ("n't", 'RB'),
 ('all', 'PDT'),
 ('that', 'DT'),
 ('bad', 'JJ'),
 ('.', '.')]

In [ ]:
# Perform standard imports


OSError: ignored

In [ ]:
!python -m spacy download xx_ent_wiki_sm

2023-08-24 05:13:14.354229: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 22.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('xx_ent_wiki_sm')


In [ ]:
!python -m spacy download xx_sent_ud_sm

2023-08-24 08:58:00.680660: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 11.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('xx_sent_ud_sm')


In [ ]:
import spacy
# nlp = spacy.load('xx_ent_wiki_sm')
nlp = spacy.load("xx_sent_ud_sm")


In [ ]:
import xx_sent_ud_sm
nlp = xx_sent_ud_sm.load()

In [ ]:
doc = nlp("This is a sentence about Facebook.")
print([(ent.text, ent.label) for ent in doc.ents])

[]


In [ ]:
doc[0].pos_

''

In [ ]:
nlp = spacy.load("xx_sent_ud_sm")
text = "Contoh kalimat dalam bahasa Indonesia."
doc = nlp(text)

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.dep_)

Contoh   
kalimat   
dalam   
bahasa   
Indonesia   
.   


In [ ]:
print(doc[4].text, doc[4].pos_, doc[4].tag_, spacy.explain(doc[4].tag_))

jumped   None


/usr/local/lib/python3.10/dist-packages/spacy/glossary.py:20: UserWarning: [W118] Term '' not found in glossary. It may however be explained in documentation for the corpora used to train the language. Please check `nlp.meta["sources"]` for any relevant links.
  warnings.warn(Warnings.W118.format(term=term))


In [ ]:
# Create a simple Doc object
doc = nlp(u"goodbye kurikulum merdeka")

In [ ]:
doc

goodbye kurikulum merdeka

In [ ]:
doc[9].pos_

IndexError: ignored

In [ ]:
for token in doc:
    print(f'{token.text:{10}} {token.pos_:{8}} {token.tag_:{6}} {spacy.explain(token.tag_)}')

goodbye                    None
kurikulum                  None
merdeka                    None


/usr/local/lib/python3.10/dist-packages/spacy/glossary.py:20: UserWarning: [W118] Term '' not found in glossary. It may however be explained in documentation for the corpora used to train the language. Please check `nlp.meta["sources"]` for any relevant links.
  warnings.warn(Warnings.W118.format(term=term))


In [ ]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 90.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 36.7 MB/s eta 0:00:00
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.12.0
    Uninstalling tensorflow-estimator-2.12.0:
      Successfully uninstalled tensorflow-estimator-2.12.0
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
  Attempting uninstall: tensorboard
    Fou

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [ ]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up",
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8435168 , -0.5132724 , -0.8884571 , ..., -0.7474884 ,
        -0.7531473 ,  0.91964483],
       [-0.87208354, -0.50543964, -0.94446665, ..., -0.85847497,
        -0.7174535 ,  0.88082975]], dtype=float32)>

In [ ]:
preprocessed_text = bert_preprocess(["hurry up"])
bert_encoder(preprocessed_text)

{'encoder_outputs': [<tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
  array([[[ 1.4382276e-01,  2.6612915e-04, -6.9811553e-02, ...,
            1.4318988e-02,  1.3345014e-03,  4.3516524e-02],
          [ 2.3877493e-01, -6.3270688e-01,  7.6440364e-01, ...,
            3.3996379e-01, -2.1870442e-01, -6.1485314e-01],
          [-7.5570032e-02, -4.1309345e-01,  7.7627555e-02, ...,
            4.9745572e-01,  6.8011180e-02,  1.2659600e-01],
          ...,
          [-1.3701521e-01, -1.7531148e-01,  6.6266870e-01, ...,
            4.7199917e-01, -4.9183622e-01,  6.7403615e-03],
          [-2.1766578e-01, -1.9481489e-01,  5.3931278e-01, ...,
            4.9001327e-01, -3.9568314e-01, -6.1026588e-02],
          [-1.1142719e-01, -1.0866638e-01,  5.4139465e-01, ...,
            8.0513018e-01, -7.1444356e-01, -1.4091074e-01]]], dtype=float32)>,
  <tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
  array([[[-0.07962665, -0.18679963, -0.17124212, ...,  0.12848622,
            0.1127079

NER Cahya

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 65.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 31.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 128.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 80.8 MB/s eta 0:00:00


In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("token-classification", model="cahya/xlm-roberta-large-indonesian-NER")

Some weights of the model checkpoint at cahya/xlm-roberta-large-indonesian-NER were not used when initializing XLMRobertaForTokenClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing XLMRobertaForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


ValueError: ignored